#!/usr/bin/env python3
"""Deterministic half of the `note-index` skill: parse, hash, and render INDEX.md.

    python3 generate_index.py scan                        # JSON, one entry per note
    python3 generate_index.py write --summaries <file>    # render .index/INDEX.md

Everything here is mechanical — extracting inline #tags and outbound links,
hashing bodies to reuse cached summaries, sorting, and rendering. The one thing
it cannot do is write a summary; the skill supplies those. Stdlib only.
"""

import hashlib
import json
import os
import re
import sys
import unicodedata
import urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import vault  # noqa: E402

_FENCE_RE = re.compile(r"```.*?```|~~~.*?~~~", re.DOTALL)
_INLINE_CODE_RE = re.compile(r"`[^`]*`")
_LINK_DEST_RE = re.compile(r"\]\([^)]*\)")
_TAG_RE = re.compile(r"(?<![\w/#.])#([A-Za-z][\w-]*(?:/[A-Za-z][\w-]*)*)")


def _strip_noise(text):
    text = _FENCE_RE.sub(" ", text)
    text = _INLINE_CODE_RE.sub(" ", text)
    text = _LINK_DEST_RE.sub("] ", text)
    return text


def extract_tags(body):
    cleaned = _strip_noise(body)
    seen = []
    for match in _TAG_RE.finditer(cleaned):
        tag = match.group(1)
        if tag not in seen:
            seen.append(tag)
    return seen


# Destination is either <...> (may contain spaces) or a run of non-space chars,
# optionally followed by a "title" — which we ignore.
_MD_LINK_RE = re.compile(r'\[[^\]]*\]\(\s*(?:<([^>]+)>|([^\s)]+))(?:\s+"[^"]*")?\s*\)')


def nfc(text):
    """Normalize to NFC so a title and a link to it compare equal.

    macOS stores filenames decomposed (NFD) and hands them back that way from
    os.listdir, while the same name typed into a note body arrives composed
    (NFC). `Té` is one code point in the note and two on disk, so a relationship
    would never match the note it names — invisibly, since both render the same.
    """
    return unicodedata.normalize("NFC", text)


def extract_relationships(body):
    cleaned = _INLINE_CODE_RE.sub(" ", _FENCE_RE.sub(" ", body))
    rels = []
    for match in _MD_LINK_RE.finditer(cleaned):
        # The note format asks for `<Angle Brackets.md>`, but a note written by
        # hand in another editor is just as likely to arrive percent-encoded —
        # Obsidian writes `Note%201.md`. Both name the same note, so decode
        # before taking the title, or the relationship lands under a mangled key.
        dest = urllib.parse.unquote((match.group(1) or match.group(2)).strip())
        if not dest.lower().endswith(".md"):
            continue
        # An attachment can be a .md file — an Excalidraw drawing is one — and a
        # note that links to it is referencing an asset, not another note. Left
        # in, it becomes a relationship to a note that will never exist.
        if "{}/".format(vault.FOLDERS["attachments"]) in dest:
            continue
        title = nfc(dest.rsplit("/", 1)[-1][:-3])
        if title and title not in rels:
            rels.append(title)
    return rels


HEADER = (
    "# INDEX\n\n"
    "> Generated by the `note-index` skill — do not edit by hand. "
    "Run the `note-index` skill to refresh.\n"
    "> Format (one line per note, alphabetical): "
    "`- [Title](<../path>) — summary · tags: a, b · relationships: A / B`\n"
)


def format_line(entry):
    # INDEX.md lives in .index/, so links climb one level to reach notes/.
    parts = ['- [{}](<../{}>) — {}'.format(
        entry["title"], entry["path"], entry["summary"].strip())]
    if entry.get("tags"):
        parts.append("tags: " + ", ".join(entry["tags"]))
    if entry.get("relationships"):
        # Separated by " / ", not ", ": a note title may contain a comma
        # ("Newton, Leibniz and the calculus") and a comma-joined list of them
        # cannot be read back. "/" is the one character a filename cannot hold,
        # so it is the only separator that stays unambiguous.
        parts.append("relationships: " + " / ".join(entry["relationships"]))
    return " · ".join(parts)


def render_index(entries):
    ordered = sorted(entries, key=lambda entry: entry["title"].casefold())
    if not ordered:
        return HEADER
    return HEADER + "\n" + "\n".join(format_line(entry) for entry in ordered) + "\n"


def load_cache(root):
    path = os.path.join(root, vault.CACHE_FILE)
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def save_cache(root, cache):
    path = os.path.join(root, vault.CACHE_FILE)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(cache, handle, ensure_ascii=False, indent=2, sort_keys=True)


def scan(root="."):
    """One entry per note under notes/, with cached summaries filled in."""
    notes_dir = os.path.join(root, vault.FOLDERS["notes"])
    if not os.path.isdir(notes_dir):
        raise SystemExit("no notes/ folder in {!r}".format(root))
    cache = load_cache(root)
    entries = []
    for name in sorted(os.listdir(notes_dir)):
        if not name.endswith(".md"):
            continue
        rel = "{}/{}".format(vault.FOLDERS["notes"], name)
        with open(os.path.join(notes_dir, name), encoding="utf-8") as handle:
            body = handle.read()
        digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
        cached = cache.get(rel)
        unchanged = cached is not None and cached.get("hash") == digest
        entries.append({
            "title": nfc(name[:-3]),
            "path": rel,
            "tags": extract_tags(body),
            "relationships": extract_relationships(body),
            "hash": digest,
            "summary": cached.get("summary") if unchanged else None,
            "needs_summary": not unchanged,
        })
    return entries


def write_index(root=".", summaries=None):
    summaries = summaries or {}
    entries = scan(root)
    cache = {}
    for entry in entries:
        provided = summaries.get(entry["path"])
        summary = provided if provided is not None else entry["summary"]
        if not summary or not summary.strip():
            raise SystemExit("missing summary for {}".format(entry["path"]))
        entry["summary"] = summary
        cache[entry["path"]] = {"hash": entry["hash"], "summary": summary}
    save_cache(root, cache)
    index_path = os.path.join(root, vault.INDEX_FILE)
    os.makedirs(os.path.dirname(index_path), exist_ok=True)
    with open(index_path, "w", encoding="utf-8") as handle:
        handle.write(render_index(entries))
    return index_path


def _resolve_root(explicit):
    if explicit:
        return os.path.abspath(os.path.expanduser(explicit))
    try:
        return vault.find_vault()
    except vault.VaultNotFound as exc:
        raise SystemExit("error: {}".format(exc))


def _main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="vault root (default: resolved via vault.py)")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("scan")
    writer = sub.add_parser("write")
    writer.add_argument("--summaries")
    args = parser.parse_args(argv)

    root = _resolve_root(args.root)
    if args.cmd == "scan":
        print(json.dumps(scan(root), ensure_ascii=False, indent=2))
        return 0

    summaries = {}
    if args.summaries:
        with open(args.summaries, encoding="utf-8") as handle:
            summaries = json.load(handle)
    print(write_index(root, summaries))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
